### ISSUE TITLE
Error when displaying the version

### ISSUE THREAD

**Issue by CyrilleHugues** [phacks/nereo-cli#2]
Hi,

I got an error on the CLI when trying to display the version. It says it does not have a package.json to refer to.
Not that I really use this feature, but you might want to fix it.

Cheers

```
nereo-cli$ version
readline.js:982
            throw err;
            ^

Error: ./package.json: ENOENT: no such file or directory, open './package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at readFileSync (/home/cyrilleh/.nvm/versions/node/v6.7.0/lib/node_modules/nereo-cli/node_modules/jsonfile/index.js:67:22)
    at getVersion (/home/cyrilleh/.nvm/versions/node/v6.7.0/lib/node_modules/nereo-cli/build/utils.js:32:37)
    at CommandInstance.<anonymous> (/home/cyrilleh/.nvm/versions/node/v6.7.0/lib/node_modules/nereo-cli/build/cli.js:55:50)
    at EventEmitter.session.execCommandSet (/home/cyrilleh/.nvm/versions/node/v6.7.0/lib/node_modules/nereo-cli/node_modules/vorpal/dist/session.js:470:20)
    at EventEmitter.vorpal._exec (/home/cyrilleh/.nvm/versions/node/v6.7.0/lib/node_modules/nereo-cli/node_modules/vorpal/dist/vorpal.js:960:18)
    at EventEmitter.vorpal._execQueueItem (/home/cyrilleh/.nvm/versions/node/v6.7.0/lib/node_modules/nereo-cli/node_modules/vorpal/dist/vorpal.js:751:17)
    at EventEmitter.vorpal._queueHandler (/home/cyrilleh/.nvm/versions/node/v6.7.0/lib/node_modules/nereo-cli/node_modules/vorpal/dist/vorpal.js:735:10)
```

**Comment by phacks** [comment]
Hi @CyrilleHugues, thanks for the report!

Should be fixed with 68b11c3be5a3b717370e90b2d31a1d52457b1b58, which was published in the `0.0.4` update.

Could you please try `npm update -g nereo-cli` and tell me whether it fixes the problem?

**Comment by CyrilleHugues** [comment]
On nereo-cli@0.0.4,

```
readline.js:982
            throw err;
            ^

Error: ./../package.json: ENOENT: no such file or directory, open './../package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
...
```
